package com.adaptivefolk;

import java.util.List;
import java.util.ArrayList;
import java.util.Random;

public class KweebecNameGenerator {
    private static final List<String> NAMES = new ArrayList<>();
    private static final Random RANDOM = new Random();

    static {
        NAMES.add("Amberbark");
        NAMES.add("Ashbloom");
        NAMES.add("Barkwhisper");
        NAMES.add("Berryshade");
        NAMES.add("Blossomveil");
        NAMES.add("Brambleheart");
        NAMES.add("Breezeflame");
        NAMES.add("Brightpetal");
        NAMES.add("Brightroot");
        NAMES.add("Budsong");
        NAMES.add("Candlefern");
        NAMES.add("Cedarveil");
        NAMES.add("Chilltwig");
        NAMES.add("Cloudberry");
        NAMES.add("Cloverbloom");
        NAMES.add("Dawnpetal");
        NAMES.add("Dewbranch");
        NAMES.add("Dewpetal");
        NAMES.add("Driftbloom");
        NAMES.add("Driftleaf");
        NAMES.add("Emberbloom");
        NAMES.add("Emberleaf");
        NAMES.add("Everthorn");
        NAMES.add("Fawnbark");
        NAMES.add("Fawnshade");
        NAMES.add("Fernwhisper");
        NAMES.add("Firebark");
        NAMES.add("Frostbloom");
        NAMES.add("Frostvine");
        NAMES.add("Glimmerbloom");
        NAMES.add("Glimmerroot");
        NAMES.add("Glowbark");
        NAMES.add("Glowfern");
        NAMES.add("Goldpetal");
        NAMES.add("Greenwhistle");
        NAMES.add("Hollowbark");
        NAMES.add("Honeystalk");
        NAMES.add("Hushleaf");
        NAMES.add("Icetwig");
        NAMES.add("Ivybloom");
        NAMES.add("Ivyleaf");
        NAMES.add("Jadebloom");
        NAMES.add("Juniperwhisper");
        NAMES.add("Leafsong");
        NAMES.add("Lightroot");
        NAMES.add("Lilacwhisper");
        NAMES.add("Loomvine");
        NAMES.add("Mossbloom");
        NAMES.add("Mossveil");
        NAMES.add("Moonfern");
        NAMES.add("Morningbark");
        NAMES.add("Nettleveil");
        NAMES.add("Nightbark");
        NAMES.add("Nightbranch");
        NAMES.add("Nightshade");
        NAMES.add("Oakwhisper");
        NAMES.add("Orchardbloom");
        NAMES.add("Orchidveil");
        NAMES.add("Palefern");
        NAMES.add("Petalbreeze");
        NAMES.add("Petalshade");
        NAMES.add("Pineglow");
        NAMES.add("Pinehollow");
        NAMES.add("Pixiebranch");
        NAMES.add("Quietbloom");
        NAMES.add("Rainbranch");
        NAMES.add("Ravenleaf");
        NAMES.add("Rosebark");
        NAMES.add("Rosebud");
        NAMES.add("Roseveil");
        NAMES.add("Rushvine");
        NAMES.add("Shadowvine");
        NAMES.add("Silverbark");
        NAMES.add("Silkpetal");
        NAMES.add("Skybloom");
        NAMES.add("Snowbranch");
        NAMES.add("Snowfern");
        NAMES.add("Solbloom");
        NAMES.add("Sparrowleaf");
        NAMES.add("Spiderbloom");
        NAMES.add("Sprigwhistle");
        NAMES.add("Starpetal");
        NAMES.add("Stonebark");
        NAMES.add("Stormbranch");
        NAMES.add("Sunbark");
        NAMES.add("Sunpetal");
        NAMES.add("Sunshard");
        NAMES.add("Thistlebloom");
        NAMES.add("Thornbark");
        NAMES.add("Thornwhisper");
        NAMES.add("Twilightbloom");
        NAMES.add("Twilightroot");
        NAMES.add("Umberleaf");
        NAMES.add("Violetbloom");
        NAMES.add("Vinewhisper");
        NAMES.add("Willowbreeze");
        NAMES.add("Windbranch");
        NAMES.add("Windpetal");
        NAMES.add("Windveil");
        NAMES.add("Winterbloom");
        NAMES.add("Winterfern");
        NAMES.add("Wispbark");
        NAMES.add("Wispvine");
        NAMES.add("Woodshade");
        NAMES.add("Yarrowbloom");
        NAMES.add("Yellowleaf");
        NAMES.add("Zephyrbark");
        NAMES.add("Zephyrfern");
        NAMES.add("Zinniawhisper");
    }

    public static String getRandomName() {
        int index = RANDOM.nextInt(NAMES.size());
        return NAMES.get(index);
    }
}